# -*- coding: utf-8 -*-
"""LagrangeInterpolationProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4uiRM2tbb3tEjvyq2ER_zowzgNmwkfo
"""

# !pip install flask pyngrok

from flask import Flask, request
# from pyngrok import ngrok
import os

# ngrok.set_auth_token("3E6Nt3kH8x4HxPzzAijUoifVUvi_3hS6dUr1FbReDDz8mu1P6")

app = Flask(__name__)
os.makedirs("./templates", exist_ok=True)

# -----------------------
# LAGRANGE FUNCTION
# -----------------------
def lagrange(x_values, y_values, x):
    n = len(x_values)
    result = 0.0

    for i in range(n):
        term = float(y_values[i])

        for j in range(n):
            if j != i:
                term *= (x - x_values[j]) / (x_values[i] - x_values[j])

        result += term

    return result

# -----------------------
# NAVBAR
# -----------------------
nav = """
<div style="background:#2c3e50; padding:12px; text-align:center;">
    <a href="/" style="color:white; margin:10px;">Home</a>
    <a href="/discussion" style="color:white; margin:10px;">Discussion</a>
    <a href="/example1" style="color:white; margin:10px;">Example 1</a>
    <a href="/example2" style="color:white; margin:10px;">Example 2</a>
    <a href="/calculator" style="color:white; margin:10px;">Calculator</a>
</div>
"""

# -----------------------
# HOME
# -----------------------
index_html = nav + """
<div style="font-family:Arial; padding:30px;">
<h1>Lagrange Interpolation Project</h1>
<p>Numerical Methods Web Application</p>
</div>
"""

# -----------------------
# DISCUSSION (EXPANDED)
# -----------------------
discussion_html = nav + """
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

<div style="font-family:Arial; padding:30px;">

<h1>📘 Lagrange Interpolation Discussion</h1>

<div style="background:white; padding:20px; border-radius:10px;">

<p>
Lagrange Interpolation is a numerical method used to estimate unknown values
from a set of known data points by constructing a polynomial that passes through all points.
</p>

<h3>📌 When it is used</h3>
<ul>
<li>Estimating missing values in data sets</li>
<li>Curve fitting</li>
<li>Engineering and scientific modeling</li>
</ul>

<h3>📌 Formula</h3>

$$P(x)=\\sum_{i=0}^{n} y_i L_i(x)$$

<h3>📌 Basis Polynomial</h3>

$$L_i(x)=\\prod_{j \\ne i} \\frac{x-x_j}{x_i-x_j}$$

<h3>📌 Idea Behind the Method</h3>

<p>
Each Lᵢ(x) becomes 1 at xᵢ and 0 at all other points.
This ensures the polynomial passes exactly through all given data points.
</p>

<h3>📌 Advantages</h3>
<ul>
<li>No system of equations required</li>
<li>Simple formula-based method</li>
<li>Works for any number of points</li>
</ul>

<h3>📌 Limitation</h3>
<ul>
<li>Becomes inefficient for large datasets</li>
<li>Polynomial may oscillate for many points</li>
</ul>

</div>
</div>
"""

# -----------------------
# EXAMPLE 1 (FULL STEP SOLUTION)
# -----------------------
example1_html = nav + """
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

<div style="font-family:Arial; padding:30px;">

<h1>Example 1</h1>

<div style="background:white; padding:20px; border-radius:10px;">

<p><b>Given:</b> (1,2), (2,4), (3,8), find f(2.5)</p>

<h3>Step 1: Formula</h3>
$$P(x)=y_0L_0(x)+y_1L_1(x)+y_2L_2(x)$$

<h3>Step 2: Compute L₀(2.5)</h3>
$$L_0(2.5)=\\frac{(2.5-2)(2.5-3)}{(1-2)(1-3)}=0.125$$

<h3>Step 3: Compute L₁(2.5)</h3>
$$L_1(2.5)=\\frac{(2.5-1)(2.5-3)}{(2-1)(2-3)}=0.75$$

<h3>Step 4: Compute L₂(2.5)</h3>
$$L_2(2.5)=\\frac{(2.5-1)(2.5-2)}{(3-1)(3-2)}=0.375$$

<h3>Step 5: Substitute into formula</h3>
$$P(2.5)=2(0.125)+4(0.75)+8(0.375)$$

<h3>Step 6: Final computation</h3>
$$P(2.5)=0.25+3+3=6.25$$

<h2 style="color:green;">Final Answer: 6.25</h2>

</div>
</div>
"""

# -----------------------
# EXAMPLE 2 (FULL STEP SOLUTION)
# -----------------------
example2_html = nav + """
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

<div style="font-family:Arial; padding:30px;">

<h1>Example 2</h1>

<div style="background:white; padding:20px; border-radius:10px;">

<p><b>Given:</b> (1,1), (3,9), find f(2)</p>

<h3>Step 1</h3>
$$P(x)=y_0L_0(x)+y_1L_1(x)$$

<h3>Step 2</h3>
$$L_0(2)=\\frac{2-3}{1-3}=0.5$$

<h3>Step 3</h3>
$$L_1(2)=\\frac{2-1}{3-1}=0.5$$

<h3>Step 4</h3>
$$P(2)=1(0.5)+9(0.5)$$

<h3>Step 5</h3>
$$P(2)=0.5+4.5=5$$

<h2 style="color:green;">Final Answer: 5</h2>

</div>
</div>
"""

# -----------------------
# CALCULATOR (STEP-BY-STEP + MATHJAX)
# -----------------------
calculator_template = nav + """
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

<div style="font-family:Arial; padding:30px;">

<h1>Calculator</h1>

<form method="POST" style="background:#f4f6f7; padding:15px; border-radius:10px; width:400px;">

<label>X values</label><br>
<input name="x_values" placeholder="1,2,3" style="width:100%; padding:8px;"><br><br>

<label>Y values</label><br>
<input name="y_values" placeholder="2,4,8" style="width:100%; padding:8px;"><br><br>

<label>Target X</label><br>
<input name="target_x" style="width:100%; padding:8px;"><br><br>

<button style="width:100%; padding:10px; background:#3498db; color:white;">
Calculate
</button>

</form>

<br>

{result}

</div>
"""

# -----------------------
# ROUTES
# -----------------------
@app.route('/')
def home():
    return index_html

@app.route('/discussion')
def discussion():
    return discussion_html

@app.route('/example1')
def example1():
    return example1_html

@app.route('/example2')
def example2():
    return example2_html

@app.route('/calculator', methods=['GET', 'POST'])
def calculator():
    result = ""
    total = 0.0

    if request.method == 'POST':

        x_values = list(map(float, request.form['x_values'].split(',')))
        y_values = list(map(float, request.form['y_values'].split(',')))
        target_x = float(request.form['target_x'])

        n = len(x_values)

        steps = "<h2>📘 Step-by-Step Solution</h2>"

        for i in range(n):
            Li = 1.0
            numerator = []
            denominator = []

            for j in range(n):
                if j != i:
                    Li *= (target_x - x_values[j]) / (x_values[i] - x_values[j])
                    numerator.append(f"(x - {x_values[j]})")
                    denominator.append(f"({x_values[i]} - {x_values[j]})")

            term = y_values[i] * Li
            total += term

            num = " \\cdot ".join(numerator)
            den = " \\cdot ".join(denominator)

            steps += f"""
            <div style="
                background:#eaf2f8;
                padding:15px;
                margin-bottom:15px;
                border-radius:10px;
                border-left:6px solid #3498db;
            ">

            <h3 style="color:#3498db;">Step {i+1}</h3>

            <p>
            $$L_{i}(x)=\\frac{{{num}}}{{{den}}}$$
            </p>

            <p>
            $$L_{i}({target_x})={Li:.6f}$$
            </p>

            <p>
            $$y_{i}L_{i}={y_values[i]}\\times{Li:.6f}={term:.6f}$$
            </p>

            </div>
            """

        steps += f"""
        <div style="
            background:#e8f5e9;
            padding:20px;
            border-radius:10px;
            border-left:6px solid #2ecc71;
        ">
        <h2 style="color:#27ae60;">Final Answer</h2>
        <p>$$P({target_x})={total:.6f}$$</p>
        </div>
        """

        result = steps

    return calculator_template.format(result=result)

# -----------------------
# RUN NGROK
# -----------------------
# ngrok.kill()
# public_url = ngrok.connect(5000)

# print("OPEN THIS LINK:", public_url)

if __name__ == '__main__':
    app.run(port=5000)

